go-sdk: Pipeline notification changes
streamdal/streamdal pull request #217
Opened 2024-02-09 15:11 UTC by blinktag

* Bump protos to v0.1.21
* Update `NotifyRequest` with new fields
* Fix README.md example

2024-02-09 21:49 UTC, dselans approved these changes
Let's get this merged!

2024-02-09 21:49 UTC, dselans commented on sdks/go/go_sdk.go
> +// TODO: simplify these params
Agreed - this is getting really long. I have to work on the SDK next, I'll do this.

2024-02-09 21:49 UTC, dselans commented on sdks/go/server/client.go
> +	Notify(ctx context.Context, pipeline *protos.Pipeline, step *protos.PipelineStep, aud *protos.Audience, payload []byte, conditionType protos.NotifyRequest_ConditionType) error
Really good that we can specify concrete types.

2024-02-10 01:31 UTC, dselans requested changes
Undo the README.md changes - I had to update it a bit ago because of the SDK migration.

2024-02-10 01:41 UTC, dselans commented
I rebased on main + removed the README updates.

2024-02-15 18:27 UTC, dselans approved these changes

2024-02-15 20:28 UTC, blinktag commented on sdks/go/README.md
> +	ctx, cancel := context.WithCancel(context.Background())
Sweet! Done

2024-02-15 20:28 UTC, blinktag commented
Waiting for frontend changes to land before merging

2024-02-16 14:52 UTC, merged